### ISSUE TITLE
Invalid render for CSS @supports

### ISSUE THREAD

**Issue by padaliyajay** [leafo/scssphp#615] opened 2018-12-24 11:57 UTC
scssphp did not rendering CSS @supports feature.

Render by scssphp (_Wrong_)
```
@supports (transform-style: preserve-3d) {
  transform: translate3d(0, 0, 0);
}
```

Render by official scss compiler (_Correct_)
```
@supports (transform-style: preserve-3d) {
  .carousel-item-next.carousel-item-left,
.carousel-item-prev.carousel-item-right {
    transform: translate3d(0, 0, 0);
  }
}
```

I am using scssphp to compile bootstrap 4 and it is working awesome. except above issue. Please test bootstrap 4.1.3 scss

I am really thankful to @leafo for this php sass compiler

**Comment by RdeWilde** [comment] 2019-01-31 12:45
Could we please get an update with this? We have the same issue and no clue how to resolve it. It should be rendered with the selector inside, but instead it is rendered next to it at root level. @leafo @robocoder

**Comment by Cerdic** [comment] 2019-04-29 08:09
I can confirm this issue:
```
.sticky-top {
  @supports (position: sticky) {
    position: sticky;
  }
}
```
compiles as
```
@supports (position: sticky) {
  position: sticky; }
```

**Comment by Cerdic** [comment] 2019-04-29 08:48
so this is a duplicate of #493

**Comment by Cerdic** [comment] 2019-05-01 16:15
(duplicate anf fixed, can be closed @robocoder)

**Closed** 2019-05-01 16:46 UTC
