### ISSUE TITLE
Undefined variable in Bootstrap 4 Alpha 6

### ISSUE THREAD

**Issue by piter2k1** [leafo/scssphp#492] opened 2017-01-25 15:50 UTC
Problematic code:
```scss
body {
    @include media-breakpoint-between(md, lg) {
        padding: 8px 0;
    }
}
```
scssphp compiler output:
`Undefined variable $min: line: 61`

I tried resolve this issue.
This is `media-breakpoint-between` code with nested mixins. All of this mixins work properly when I use they separately.
```scss
@mixin media-breakpoint-between($lower, $upper, $breakpoints: $grid-breakpoints) {
  @include media-breakpoint-up($lower, $breakpoints) {
    @include media-breakpoint-down($upper, $breakpoints) {
      @content;
    }
  }
}
```

Variable **$min** is in `media-breakpoint-up` mixin:
```scss
@mixin media-breakpoint-up($name, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($name, $breakpoints);
  @if $min {
    @media (min-width: $min) {
      @content;
    }
  } @else {
    @content;
  }
}
```

This works properly:
```scss
body {
    @include media-breakpoint-up(md) {
        padding: 8px 0;
    }
}
```
and
```scss
body {
    @include media-breakpoint-down(lg) {
        padding: 8px 0;
    }
}
```

I used 0.6.6 version of scssphp and latest from branch master.

**Comment by robocoder** [comment] 2017-01-27 15:33
Appears to be a duplicate of the scope issue reported in #446

**Comment by eliavm** [comment] 2017-06-29 05:25
Did you find a solution? I'm running into the same problem when trying to compile material design for angular (https://github.com/angular/material2)

`Undefined variable $mat-input-infix-padding: line: 2441`

**Comment by tikitariki** [comment] 2018-02-14 22:41
Not the most graceful solution, but as a workaround you can refactor your SCSS. I had a media query within a media query. Doing things differently allowed it to compile.

**Comment by Cerdic** [comment] 2019-05-01 18:10
Seems a duplicate of #423 also

**Comment by Cerdic** [comment] 2019-05-09 08:27
Full test case:
```
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 768px,
  lg: 992px,
  xl: 1200px
) !default;


// Name of the next breakpoint, or null for the last breakpoint.
//
//    >> breakpoint-next(sm)
//    md
//    >> breakpoint-next(sm, (xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1200px))
//    md
//    >> breakpoint-next(sm, $breakpoint-names: (xs sm md lg xl))
//    md
@function breakpoint-next($name, $breakpoints: $grid-breakpoints, $breakpoint-names: map-keys($breakpoints)) {
  $n: index($breakpoint-names, $name);
  @return if($n != null and $n < length($breakpoint-names), nth($breakpoint-names, $n + 1), null);
}

// Minimum breakpoint width. Null for the smallest (first) breakpoint.
//
//    >> breakpoint-min(sm, (xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1200px))
//    576px
@function breakpoint-min($name, $breakpoints: $grid-breakpoints) {
  $min: map-get($breakpoints, $name);
  @return if($min != 0, $min, null);
}

// Maximum breakpoint width. Null for the largest (last) breakpoint.
// The maximum value is calculated as the minimum of the next one less 0.02px
// to work around the limitations of `min-` and `max-` prefixes and viewports with fractional widths.
// See https://www.w3.org/TR/mediaqueries-4/#mq-min-max
// Uses 0.02px rather than 0.01px to work around a current rounding bug in Safari.
// See https://bugs.webkit.org/show_bug.cgi?id=178261
//
//    >> breakpoint-max(sm, (xs: 0, sm: 576px, md: 768px, lg: 992px, xl: 1200px))
//    767.98px
@function breakpoint-max($name, $breakpoints: $grid-breakpoints) {
  $next: breakpoint-next($name, $breakpoints);
  @return if($next, breakpoint-min($next, $breakpoints) - .02, null);
}


// Media of at least the minimum breakpoint width. No query for the smallest breakpoint.
// Makes the @content apply to the given breakpoint and wider.
@mixin media-breakpoint-up($name, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($name, $breakpoints);
  @if $min {
    @media (min-width: $min) {
      @content;
    }
  } @else {
    @content;
  }
}

// Media of at most the maximum breakpoint width. No query for the largest breakpoint.
// Makes the @content apply to the given breakpoint and narrower.
@mixin media-breakpoint-down($name, $breakpoints: $grid-breakpoints) {
  $max: breakpoint-max($name, $breakpoints);
  @if $max {
    @media (max-width: $max) {
      @content;
    }
  } @else {
    @content;
  }
}

// Media that spans multiple breakpoint widths.
// Makes the @content apply between the min and max breakpoints
@mixin media-breakpoint-between($lower, $upper, $breakpoints: $grid-breakpoints) {
  $min: breakpoint-min($lower, $breakpoints);
  $max: breakpoint-max($upper, $breakpoints);

  @if $min != null and $max != null {
    @media (min-width: $min) and (max-width: $max) {
      @content;
    }
  } @else if $max == null {
    @include media-breakpoint-up($lower, $breakpoints) {
      @content;
    }
  } @else if $min == null {
    @include media-breakpoint-down($upper, $breakpoints) {
      @content;
    }
  }
}

body {
    @include media-breakpoint-between(md, lg) {
        padding: 8px 0;
    }
}
```

Works fine now:
```
@media (min-width: 768px) and (max-width: 1199.98px) {
    body {
      padding: 8px 0; } }
```

This issue can be closes @robocoder

**Closed** 2019-05-09 16:41 UTC
Labels: duplicate
