### ISSUE TITLE
Variable nesting or scoping issue since v0.31

### ISSUE THREAD

**Issue by dleffler** [leafo/scssphp#380] opened 2015-11-12 21:59 UTC
This is an attempt to reopen ticket #337...in the real world, variables seem to get lost when wrapping bootstrap v3.3.5 with another file and passing in variables...here is a test using 3 files to demonstrate the issue...compiling _test.scss (which imports _test_1.scss) below works, but wrapping it with _test_2.scss (which imports _test.scss which in turn imports _test_1.scss) fails

**_test.scss**

``` sass
$asset-helper: false !default;
$icon-font-path: if($asset-helper, "bootstrap/", "../fonts/bootstrap/") !default;
$icon-font-name:          "glyphicons-halflings-regular" !default;
@at-root {
  // Import the fonts
  @font-face {
    font-family: 'Glyphicons Halflings';
    src: url(if($asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.eot'), '#{$icon-font-path}#{$icon-font-name}.eot'));
  }
}
$test-1: 1px;
@import "test_1";

.one {
  width: $test-1;
}
```

**_test_1.scss**

``` sass
.onein1 {
  width: $test-1;
}
@at-root {
  // Import the fonts
  @font-face {
    font-family: 'Glyphicons Halflings';
    src: url(if($asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.eot'), '#{$icon-font-path}#{$icon-font-name}.eot'));
  }
}
```

**_test_2.scss**

``` sass
.exp-skin {
    $test-2: 2px;

    @import "test";
}
```

**Comment by robocoder** [comment] 2015-11-12 23:40
I'd rather keep this one open since it contains a test case.

**Comment by dleffler** [comment] 2016-02-13 02:52
I was able to verify the above test compiles correctly in ruby sass v3.4.9

**Comment by dleffler** [comment] 2016-10-28 18:11
Actually seems to be tied to sub-classing and not with import. If you wrap boostrap3 or 4 scss file with
```sass
.my-skin {
    //...original bootstrap.scss contents...
}
```
you'll receive the same error and inability to compile

**Comment by Cerdic** [comment] 2019-06-04 07:51
OK looks like we made some progress on this issue, fixing all other bugs.

If the `_test2.scss` is still failing it's only due to the at-root var lookup:
```
./bin/pscss _test2.scss

Fatal error: Uncaught Leafo\ScssPhp\Exception\CompilerException: Undefined variable $asset-helper: _test.scss on line 8, at column 5 in /Users/cedric/Sites/scssphp/src/Compiler.php:4169
Stack trace:
#0 /Users/cedric/Sites/scssphp/src/Compiler.php(3795): Leafo\ScssPhp\Compiler->throwError('Undefined varia...')
#1 /Users/cedric/Sites/scssphp/src/Compiler.php(2686): Leafo\ScssPhp\Compiler->get('asset-helper')
#2 /Users/cedric/Sites/scssphp/src/Compiler.php(4955): Leafo\ScssPhp\Compiler->reduce(Array, true)
#3 [internal function]: Leafo\ScssPhp\Compiler->libIf(Array, Array)
#4 /Users/cedric/Sites/scssphp/src/Compiler.php(4313): call_user_func(Array, Array, Array)
#5 /Users/cedric/Sites/scssphp/src/Compiler.php(2752): Leafo\ScssPhp\Compiler->callNativeFunction('if', Array, NULL)
#6 /Users/cedric/Sites/scssphp/src/Compiler.php(2724): Leafo\ScssPhp\Compiler->fncall('if', Array)
#7 /Users/cedric/Sites/scssphp/src/Compiler.php(2761): Leafo\ScssPhp\Compiler->reduce(Array)
#8 /Users/cedric/Sites/scssphp/src/Compiler.php(2724): Leafo in /Users/cedric/Sites/scssphp/src/Compiler.php on line 4169
```

and this a nothing to do with `@import` because

1. I can reproduce with simple the following test case without `@import`:
```
.exp-skin {
  $asset-helper: false !default;
  $icon-font-path: if($asset-helper, "bootstrap/", "../fonts/bootstrap/") !default;
  $icon-font-name: "glyphicons-halflings-regular" !default;
  @at-root {
    // Import the fonts
    @font-face {
      font-family: 'Glyphicons Halflings';
      src: url(if($asset-helper, twbs-font-path('#{$icon-font-path}#{$icon-font-name}.eot'), '#{$icon-font-path}#{$icon-font-name}.eot'));
    }
  }
}
```

2. I can have a successful compiling of `_test2.scss` if I'm just commenting the 'src:..' line in `_test.scss` and `_test1.scss` and that shows that the scoping variable is fixed

**Comment by Cerdic** [comment] 2019-06-04 09:06
and this is fully fixed with #704

**Comment by Cerdic** [comment] 2019-06-04 12:29
this one can also be closed @robocoder

**Comment by robocoder** [comment] 2019-06-04 12:57
Thanks again!

**Closed by robocoder** 2019-06-04 12:57 UTC
Labels: has-test-case
