### ISSUE TITLE
@supports doesn't work in Bootstrap

### ISSUE THREAD

**Issue by AdamPerkins** [leafo/scssphp#574] opened 2018-05-17 09:23 UTC
I have compiled Bootstrap 4.1.1 and got some issues. 

SCSS in _positions.scss of Bootstrap
~~~
.sticky-top {
  @supports (position: sticky) {
    position: sticky;
    top: 0;
    z-index: $zindex-sticky;
  }
~~~
Output scssphp:
~~~
@supports (position: sticky) {
  position: sticky;
  top: 0;
  z-index: 1020;
}
~~~
Should be this:
~~~
@supports ((position: -webkit-sticky) or (position: sticky)) {
  .sticky-top {
    position: -webkit-sticky;
    position: sticky;
    top: 0;
    z-index: 1020; } }
~~~

Or like this without vendor prefix (Created with Koala):
~~~
@supports (position: sticky) {
  .sticky-top {
    position: sticky;
    top: 0;
    z-index: 1020; } }
~~~

**Comment by sbuckpesch** [comment] 2018-05-23 09:46
+1

**Comment by robocoder** [comment] 2018-05-27 13:07
Duplicate of #493

**Closed by robocoder** 2018-05-27 13:07 UTC
