### ISSUE TITLE
ParserException: parse error: failed at `$b: &; `

### ISSUE THREAD

**Issue by upqode-bohdan** [leafo/scssphp#650] opened 2019-04-26 09:00 UTC
Release v0.7.8

Fatal error: Uncaught Leafo\ScssPhp\Exception\ParserException: parse error: failed at `$b: &; ` D:\OSPanel\domains\test-multisite.local/wp-content/themes/bs-new/assets/scss/partials/_search-main.scss on line 5 in D:\OSPanel\domains\test-multisite.local\wp-content\themes\bs-new\lib\scssphp\src\Parser.php:128 Stack trace: #0 D:\OSPanel\domains\test-multisite.local\wp-content\themes\bs-new\lib\scssphp\src\Parser.php(169): Leafo\ScssPhp\Parser->throwParseError()
#1 D:\OSPanel\domains\test-multisite.local\wp-content\themes\bs-new\lib\scssphp\src\Compiler.php(3478): Leafo\ScssPhp\Parser->parse('/* ------------...')
#2 D:\OSPanel\domains\test-multisite.local\wp-content\themes\bs-new\lib\scssphp\src\Compiler.php(1538): Leafo\ScssPhp\Compiler->importFile('D:\\OSPanel\\doma...', Object(Leafo\ScssPhp\Formatter\OutputBlock))
#3 D:\OSPanel\domains\test-multisite.local\wp-content\themes\bs-new\lib\scssphp\src\Compiler.php(1596): Leafo\ScssPhp\Compiler->compileImport(Array, Object(Leafo\ScssPhp\Formatter\OutputBlock))
#4 D:\OSPanel\doma in D:\OSPanel\domains\test-multisite.local\wp-content\themes\bs-new\lib\scssphp\src\Parser.php on line 128

**Comment by Cerdic** [comment] 2019-04-29 08:00
Can you please provide some more information, like: did it compile or not with a previous version? wich one? Can you provide some sample code to reproduce the problem?

As is, except of knowing that "it fails in a certain case" this issue is not very helpful…

**Comment by Cerdic** [comment] 2019-04-29 08:40
OK, this is a duplicate of #620

**Comment by Cerdic** [comment] 2019-05-01 16:09
duplicate + this is fixed now, can be closed @robocoder

**Closed** 2019-05-01 16:49 UTC
