### ISSUE TITLE
Parse error: failed at `&} in bootstrap 4.3

### ISSUE THREAD

**Issue by padaliyajay** [leafo/scssphp#637] opened 2019-03-22 16:49 UTC
Getting this error while compiling bootstrap 4.3. can you please fix it?
`Parse error: failed at &}`

Bootstrap 4 scss code

```
@mixin badge-variant($bg) {
  color: color-yiq($bg);
  background-color: $bg;

  @at-root a#{&} {
    @include hover-focus {
      color: color-yiq($bg);
      background-color: darken($bg, 10%);
    }

    &:focus,
    &.focus {
      outline: 0;
      box-shadow: 0 0 0 $badge-focus-width rgba($bg, .5);
    }
  }
}
```

**Comment by dleffler** [comment] 2019-03-23 12:36
Looks like a duplicate of Issue #616

**Comment by padaliyajay** [comment] 2019-03-28 11:15
Fixed By Modifying bootstrap code

Replace `@at-root a#{&}` to `&[href]` in following files

bootstrap4/mixins/_badge.scss
bootstrap4/_badge.scss

**Comment by robocoder** [comment] 2019-04-24 18:49
Closing as a dupe of #616

**Closed by robocoder** 2019-04-24 18:49 UTC
Labels: duplicate
