### ISSUE TITLE
Undefined variable error in nested mixins

### ISSUE THREAD

**Issue by fkalka** [leafo/scssphp#511] opened 2017-04-10 14:41 UTC
Hi,
i hope this was not reported before. There are a few similar issues, but i think this is something else.
The following code fails with "Undefined variable $d1: line: 12". On line 12 there is only a "}".

```
@mixin d1() {
  $d1: 450px;
  @media (min-width: $d1) {
    @content;
  }
}

@mixin d2() {
  $d2: 500px;
  @media (max-width: $d2) {
    @content;
  }
}

@mixin d3() {
  @include d1() {
    @include d2() {
      background-color: pink !important;
    }
  }
}

body {
  @include d3();
}
```

I compiled it with libsass w/o an error.

I will debug a bit, maybe i can find the problem.
But any hints are very welcome :)

Thanks

**Comment by willpower232** [comment] 2017-04-10 19:56
something that might help your investigation, I have a similar use of mixins it works but it looks more like this (note the separation of the px):
```
$abc: 500;
...
@media (max-width: $abc + px) {
    ...
}

**Comment by fkalka** [comment] 2017-04-11 09:46
Do you nest the mixins like in my example? If so, can you please post a full example?

**Comment by dleffler** [comment] 2017-04-12 12:59
Is this another variation of issue #380?

**Comment by piter2k1** [comment] 2017-04-13 12:51
The same problem as in #492, nested @include...

**Comment by jason-engage** [comment] 2017-09-07 07:43
I'm seeing this 'undefined variable' error but under @keyframes

@keyframes checkmark {
   ...
   20% {
        height: 0;
        width: $check-width;
        opacity: 1;
      }
...

**Comment by Cerdic** [comment] 2019-05-01 18:14
also a duplicate of #423

**Closed** 2019-05-08 20:31 UTC
