### ISSUE TITLE
Parser error - "bootstrap": "v4.0.0-alpha.2",

### ISSUE THREAD

**Issue by hanzx** [leafo/scssphp#449] opened 2016-06-29 07:44 UTC
[Leafo\ScssPhp\Exception\CompilerException]  
  Undefined variable $i: line: 32

**Comment by robocoder** [comment] 2016-07-12 03:09
Not enough info.

**Comment by FMCorz** [comment] 2016-07-12 07:16
I think that this is covered in #446.

**Comment by JumpLink** [comment] 2016-07-12 11:49
Any workaround?

**Comment by FMCorz** [comment] 2016-07-12 12:54
@JumpLink I've linked a patch on #446 if you want to give it a shot, though I would definitely not recommend using that in production. Note that other issues report some invalid compilation of Boostrap even though it does not fail.

**Comment by MrNicodemuz** [comment] 2016-07-29 06:18
I'm getting the same problem in alpha 3:
```
[Leafo\ScssPhp\Exception\CompilerException]
  Undefined variable $i: line: 48
```

**Comment by array-pop-tarts** [comment] 2016-08-14 06:44
I have exactly the same issue in alpha 3:
```
[Leafo\ScssPhp\Exception\CompilerException]
Undefined variable $i: line: 48
```
leafo/scssphp is the recommended compiler for Symfony 3. Not sure what to do if it doesn't work. Any word on when this will be fixed?

**Comment by o** [comment] 2016-08-15 07:56
Hi there,

I have same issue with latest zurb foundation
Temporarily i switched to sass compiler

```
assetic:
    debug:          "%kernel.debug%"
    use_controller: '%kernel.debug%'
    bundles:        ["AppBundle"]
    #java: /usr/bin/java
    workers:
        cache_busting:
            enabled: true
    filters:
        cssrewrite: ~
        closure:
            jar: "%kernel.root_dir%/Resources/java/closure-compiler-v20160713.jar"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        sass:    ~
    ruby: "/usr/bin/ruby -Eutf-8"
```

**Comment by Spy-Seth** [comment] 2016-09-10 22:50
I've alo the issue with the alpha 4. Any idea on how fix this?

**Comment by robocoder** [comment] 2016-09-18 23:45
Closing this as a dupe of #446

**Closed by robocoder** 2016-09-18 23:45 UTC
Labels: needs-test
