### ISSUE TITLE
@import wildcard support

### ISSUE THREAD

**Issue by gmorse81** [leafo/scssphp#482] opened 2016-12-14 19:24 UTC
I would like to be able to use something like this in my style.scss:

`@import "pages/*"`

This would import all files found in the pages directory. Is this supported now or are there any future plans?

**Comment by robocoder** [comment] 2016-12-21 20:37
Duplicate of #210. No plans until this is supported by ruby scss.

**Closed by robocoder** 2016-12-21 20:37 UTC
